version: '3.8'

services:
  web:
    image: php:7.4-apache
    ports:
      - "8086:80"
    depends_on:
      - db
    networks:
      - support_tickets_network

  db:
    image: mysql:5.7
    container_name: support_tickets_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: support_tickets
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3307:3306"  # Assure-toi que le port MySQL est bien exposé sur le port 3306
    networks:
      - support_tickets_network

networks:
  support_tickets_network:
    driver: bridge
